# =========== protocol =========== 
set (PROJECT_PROTOCOL_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR})
set (PROJECT_PROTOCOL_INC_DIR "${PROJECT_PROTOCOL_ROOT_DIR}/include")
set (PROJECT_PROTOCOL_PROTO_DIR "${PROJECT_PROTOCOL_ROOT_DIR}/proto")
set (PROJECT_PROTOCOL_SRC_DIR "${PROJECT_PROTOCOL_ROOT_DIR}/src")

include_directories(${PROJECT_PROTOCOL_INC_DIR})
include_directories(${PROJECT_PROTOCOL_PROTO_DIR})
